### ISSUE TITLE
Setup.R

### ISSUE THREAD

**Issue by ShahnurIslam** [MichaelJW/gscsv#1]
Hey Michael,

Thanks for putting together this project, really useful. I think I've got all the information I need to set it up. One thing in your repo, I couldn't find the 'Setup.R' file. Is it meant to be included or have I missed a step?

Thanks,
Shan

**Comment by MichaelJW** [comment]
Thanks @ShahnurIslam! Somehow I managed to commit the R files to my local repo but not sync that change to GitHub! Just done that now. Cheers for bringing that to my attention, and please let me know if you have any questions :)
